from fastapi import APIRouter
from app.core.responses import ok
router=APIRouter()
@router.get("/users")
async def users(): return ok([{ "id":1001,"name":"Demo Farmer","role":"FARMER","status":"active" }])
@router.get("/farmers")
async def farmers(): return ok([{ "id":101,"name":"Ramesh Patil","verification":"verified" }])
@router.get("/buyers")
async def buyers(): return ok([{ "id":201,"business_name":"FreshMart Foods","verification":"verified" }])
@router.get("/orders")
async def orders(): return ok([{ "id":9001,"status":"confirmed","amount":14000 }])
@router.get("/crops")
async def crops(): return ok([{ "id":1,"crop":"Tomato","status":"available" }])
@router.get("/bids")
async def bids(): return ok([{ "id":7001,"status":"active","bid_price":28 }])
@router.get("/rescue")
async def rescue(): return ok([{ "id":8001,"urgency":"high","status":"active" }])
@router.get("/waste")
async def waste(): return ok([{ "id":8501,"type":"Tomato stalk","status":"available" }])
@router.post("/users/{user_id}/suspend")
async def suspend(user_id:int): return ok({"user_id":user_id,"status":"suspended"})
@router.post("/users/{user_id}/activate")
async def activate(user_id:int): return ok({"user_id":user_id,"status":"active"})
@router.post("/crops/{crop_id}/remove")
async def remove_crop(crop_id:int): return ok({"crop_id":crop_id,"removed":True})
@router.get("/analytics/users")
async def analytics_users(): return ok({"total":1240,"farmers":780,"buyers":210,"customers":220,"fpos":30})
@router.get("/analytics/orders")
async def analytics_orders(): return ok({"total":4820,"completed":4510,"cancelled":110,"pending":200})
@router.get("/analytics/revenue")
async def revenue(): return ok({"gross_revenue":18450000,"farmer_payout":16120000,"platform_revenue":2330000,"currency":"INR"})
@router.get("/analytics/crops")
async def crops_analytics(): return ok([{ "crop":"Tomato","volume_kg":240000},{"crop":"Onion","volume_kg":190000}])
@router.get("/audit-logs")
async def audit_logs(): return ok([{ "id":1,"actor_id":1001,"action":"CROP_CREATED","resource":"crop:1","timestamp":"2026-09-13T10:00:00Z"}])
@router.get("/audit-logs/{log_id}")
async def audit_log(log_id:int): return ok({"id":log_id,"action":"CROP_CREATED","resource":"crop:1"})
