from fastapi import APIRouter
from app.core.responses import ok
router=APIRouter()
@router.get("")
async def notifications(): return ok([{ "id":1,"type":"BID","title":"New bid received","message":"FreshMart Foods bid ₹28/kg for Tomato","read":False,"created_at":"2026-09-13T10:00:00Z"}])
@router.get("/unread")
async def unread(): return ok([{ "id":1,"title":"New bid received","read":False}],count=1)
@router.post("/item/{notification_id}/read")
async def read(notification_id:int): return ok({"id":notification_id,"read":True})
@router.post("/read-all")
async def read_all(): return ok({"updated":4})
@router.delete("/item/{notification_id}")
async def delete(notification_id:int): return ok({"id":notification_id,"deleted":True})
@router.get("/preferences")
async def preferences(): return ok({"push":True,"sms":True,"email":True,"bid_alerts":True,"price_alerts":True,"delivery_alerts":True})
@router.patch("/preferences")
async def update_preferences(): return ok({"updated":True})
