from fastapi import APIRouter
from app.core.responses import ok
router=APIRouter()
@router.get("")
async def orders(): return ok([{ "id":9001,"buyer_id":201,"farmer_id":101,"total_amount":14000,"status":"confirmed","payment_status":"pending","delivery_status":"scheduled"}])
@router.post("")
async def create_order(): return ok({"id":9002,"status":"pending_payment","total_amount":14000},"Order created")
@router.get("/{order_id}")
async def get_order(order_id:int): return ok({"id":order_id,"status":"confirmed","total_amount":14000,"items":[{"crop_id":1,"quantity":500,"price_per_kg":28}]})
@router.patch("/{order_id}")
async def update_order(order_id:int): return ok({"id":order_id,"updated":True})
@router.get("/{order_id}/items")
async def items(order_id:int): return ok([{ "crop_id":1,"crop_name":"Tomato","quantity":500,"unit_price":28,"subtotal":14000 }])
@router.post("/{order_id}/items")
async def add_item(order_id:int): return ok({"order_id":order_id,"item_added":True})
@router.post("/{order_id}/confirm")
async def confirm(order_id:int): return ok({"id":order_id,"status":"confirmed"})
@router.post("/{order_id}/cancel")
async def cancel(order_id:int): return ok({"id":order_id,"status":"cancelled"})
@router.post("/{order_id}/accept")
async def accept(order_id:int): return ok({"id":order_id,"status":"accepted"})
@router.post("/{order_id}/reject")
async def reject(order_id:int): return ok({"id":order_id,"status":"rejected"})
