from fastapi import APIRouter
from app.core.responses import ok
router=APIRouter()
@router.get("")
async def waste(): return ok([{ "id":8501,"farmer_id":101,"type":"Tomato stalk","quantity":800,"unit":"kg","use":"cattle_feed","price_per_kg":4,"location":"Pune","status":"available"}])
@router.post("")
async def create_waste(): return ok({"id":8502,"status":"available"},"Waste listing created")
@router.get("/detail/{waste_id}")
async def get_waste(waste_id:int): return ok({"id":waste_id,"type":"Tomato stalk","quantity":800,"unit":"kg","use":"cattle_feed"})
@router.patch("/{waste_id}")
async def update_waste(waste_id:int): return ok({"id":waste_id,"updated":True})
@router.delete("/{waste_id}")
async def delete_waste(waste_id:int): return ok({"id":waste_id,"deleted":True})
@router.get("/search")
async def search(): return ok([{ "id":8501,"type":"Tomato stalk","use":"cattle_feed","price_per_kg":4 }])
@router.get("/nearby")
async def nearby(): return ok([{ "id":8501,"distance_km":7.4,"type":"Tomato stalk","quantity":800 }])
