from enum import StrEnum


class AccountStatus(StrEnum):
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    LOCKED = "LOCKED"
    DISABLED = "DISABLED"
    
class OTPPurpose(StrEnum):
    REGISTER = "REGISTER"
    LOGIN = "LOGIN"
    CHANGE_PHONE = "CHANGE_PHONE"
    RESET_PIN = "RESET_PIN"
    
    
class AuthEventType(StrEnum):
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILED = "LOGIN_FAILED"

    OTP_REQUESTED = "OTP_REQUESTED"
    OTP_VERIFIED = "OTP_VERIFIED"
    OTP_FAILED = "OTP_FAILED"

    LOGOUT = "LOGOUT"

    ACCOUNT_LOCKED = "ACCOUNT_LOCKED"
    ACCOUNT_UNLOCKED = "ACCOUNT_UNLOCKED"

    PHONE_CHANGED = "PHONE_CHANGED"
    PIN_CHANGED = "PIN_CHANGED"